name: Python CI

on:
  push:
    branches:
      - main  # Trigger the workflow for push events to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow for pull requests targeting 'main' branch

jobs:
  test:
    runs-on: ubuntu-latest  # The operating system for the CI environment
    strategy:
      matrix:
        python-version: [3.8, 3.12]  # Matrix to run on both Python 3.8 and 3.12

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install . # Install your package locally
          pip install pytest

      # Step 4: Run tests
      - name: Run tests with pytest
        run: |
          pytest --maxfail=1 --disable-warnings -q  # Optional pytest arguments (e.g., stop after 1 failure)
